# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RacchaiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('twitter_url', models.URLField()),
            ],
            options={
                'db_table': 'racchai_user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
