# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170514_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_emp',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('emp_num', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('email_address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
